export const videoMap = {
  "rain": "/demo_dataset/rain-1.mp4",
  "rainbow": "/demo_dataset/Rainbow.mp4",
  "rajasthan": "/demo_dataset/rajasthan.mp4",
  "ram": "/demo_dataset/ram.mp4",
  "ramzan": "/demo_dataset/ramzan.mp4",
  "random motion": "/demo_dataset/Random Motion.mp4",
  "random": "/demo_dataset/Random.mp4",
  "range": "/demo_dataset/Range.mp4",
  "rank": "/demo_dataset/Rank.mp4",
  "rapldly": "/demo_dataset/Rapldly.mp4",
  "rat": "/demo_dataset/rat.mp4",
  "rate differential": "/demo_dataset/Rate Differential.mp4",
  "rate": "/demo_dataset/Rate.mp4",
  "ratification": "/demo_dataset/Ratification.mp4",
  "ratio": "/demo_dataset/Ratio.mp4",
  "re employment": "/demo_dataset/Re Employment.mp4",
  "re endorsed": "/demo_dataset/Re Endorsed.mp4",
  "re examine": "/demo_dataset/Re Examine.mp4",
  "re issue": "/demo_dataset/Re Issue.mp4",
  "re pledge": "/demo_dataset/Re Pledge.mp4",
  "re sale": "/demo_dataset/Re Sale.mp4",
  "reach": "/demo_dataset/reach.mp4",
  "reaction": "/demo_dataset/Reaction.mp4",
  "read": "/demo_dataset/read.mp4",
  "reai imege": "/demo_dataset/Reai Imege.mp4",
  "real": "/demo_dataset/real.mp4",
  "reason": "/demo_dataset/Reason.mp4",
  "reasonable notice": "/demo_dataset/Reasonable Notice.mp4",
  "rebate": "/demo_dataset/Rebate.mp4",
  "recall": "/demo_dataset/Recall.mp4",
  "receipt": "/demo_dataset/Receipt.mp4",
  "receive": "/demo_dataset/Receive.mp4",
  "receiver": "/demo_dataset/Receiver.mp4",
  "recognise": "/demo_dataset/recognise.mp4",
  "recommendation": "/demo_dataset/Recommendation.mp4",
  "reconciliation": "/demo_dataset/Reconciliation.mp4",
  "reconsider": "/demo_dataset/Reconsider.mp4",
  "record": "/demo_dataset/Record.mp4",
  "recover": "/demo_dataset/Recover.mp4",
  "recruitment": "/demo_dataset/Recruitment.mp4",
  "rectange": "/demo_dataset/rectange.mp4",
  "rectangle": "/demo_dataset/Rectangle.mp4",
  "rectification": "/demo_dataset/Rectification.mp4",
  "rectifier": "/demo_dataset/Rectifier.mp4",
  "recurring": "/demo_dataset/Recurring.mp4",
  "red": "/demo_dataset/Red.mp4",
  "redlation": "/demo_dataset/Redlation.mp4",
  "reduce": "/demo_dataset/Reduce.mp4",
  "refer to drawer": "/demo_dataset/Refer To Drawer.mp4",
  "refinance": "/demo_dataset/Refinance.mp4",
  "reflection": "/demo_dataset/Reflection.mp4",
  "reform": "/demo_dataset/Reform.mp4",
  "refraction": "/demo_dataset/Refraction.mp4",
  "refresher course": "/demo_dataset/Refresher Course.mp4",
  "refretive index": "/demo_dataset/Refretive Index.mp4",
  "refrigerater": "/demo_dataset/refrigerater.mp4",
  "refrigerator": "/demo_dataset/Refrigerator.mp4",
  "refund": "/demo_dataset/Refund.mp4",
  "refusal": "/demo_dataset/Refusal.mp4"
};
