export const videoMap = {
  "rain": "/Part1/rain-1.mp4",
  "rainbow": "/Part1/Rainbow.mp4",
  "rajasthan": "/Part1/rajasthan.mp4",
  "ram": "/Part1/ram.mp4",
  "ramzan": "/Part1/ramzan.mp4",
  "random motion": "/Part1/Random Motion.mp4",
  "random": "/Part1/Random.mp4",
  "range": "/Part1/Range.mp4",
  "rank": "/Part1/Rank.mp4",
  "rapldly": "/Part1/Rapldly.mp4",
  "rat": "/Part1/rat.mp4",
  "rate differential": "/Part1/Rate Differential.mp4",
  "rate": "/Part1/Rate.mp4",
  "ratification": "/Part1/Ratification.mp4",
  "ratio": "/Part1/Ratio.mp4",
  "re employment": "/Part1/Re Employment.mp4",
  "re endorsed": "/Part1/Re Endorsed.mp4",
  "re examine": "/Part1/Re Examine.mp4",
  "re issue": "/Part1/Re Issue.mp4",
  "re pledge": "/Part1/Re Pledge.mp4",
  "re sale": "/Part1/Re Sale.mp4",
  "reach": "/Part1/reach.mp4",
  "reaction": "/Part1/Reaction.mp4",
  "read": "/Part1/read.mp4",
  "reai imege": "/Part1/Reai Imege.mp4",
  "real": "/Part1/real.mp4",
  "reason": "/Part1/Reason.mp4",
  "reasonable notice": "/Part1/Reasonable Notice.mp4",
  "rebate": "/Part1/Rebate.mp4",
  "recall": "/Part1/Recall.mp4",
  "receipt": "/Part1/Receipt.mp4",
  "receive": "/Part1/Receive.mp4",
  "receiver": "/Part1/Receiver.mp4",
  "recognise": "/Part1/recognise.mp4",
  "recommendation": "/Part1/Recommendation.mp4",
  "reconciliation": "/Part1/Reconciliation.mp4",
  "reconsider": "/Part1/Reconsider.mp4",
  "record": "/Part1/Record.mp4",
  "recover": "/Part1/Recover.mp4",
  "recruitment": "/Part1/Recruitment.mp4",
  "rectange": "/Part1/rectange.mp4",
  "rectangle": "/Part1/Rectangle.mp4",
  "rectification": "/Part1/Rectification.mp4",
  "rectifier": "/Part1/Rectifier.mp4",
  "recurring": "/Part1/Recurring.mp4",
  "red": "/Part1/Red.mp4",
  "redlation": "/Part1/Redlation.mp4",
  "reduce": "/Part1/Reduce.mp4",
  "refer to drawer": "/Part1/Refer To Drawer.mp4",
  "refinance": "/Part1/Refinance.mp4",
  "reflection": "/Part1/Reflection.mp4",
  "reform": "/Part1/Reform.mp4",
  "refraction": "/Part1/Refraction.mp4",
  "refresher course": "/Part1/Refresher Course.mp4",
  "refretive index": "/Part1/Refretive Index.mp4",
  "refrigerater": "/Part1/refrigerater.mp4",
  "refrigerator": "/Part1/Refrigerator.mp4",
  "refund": "/Part1/Refund.mp4",
  "refusal": "/Part1/Refusal.mp4",
  "region": "/Part1/Region.mp4",
  "register": "/Part1/Register.mp4",
  "registered letter": "/Part1/Registered Letter.mp4",
  "registered": "/Part1/Registered.mp4",
  "registrar": "/Part1/Registrar.mp4",
  "regret": "/Part1/regret.mp4",
  "regularisation": "/Part1/Regularisation.mp4",
  "regulation": "/Part1/Regulation.mp4",
  "regutar vibration": "/Part1/Regutar Vibration.mp4",
  "reimbrusement": "/Part1/Reimbrusement.mp4",
  "reject": "/Part1/reject.mp4",
  "rejoinder": "/Part1/Rejoinder.mp4",
  "relative": "/Part1/relative-1.mp4",
  "release": "/Part1/Release.mp4",
  "remember": "/Part1/remember-1.mp4",
  "remind": "/Part1/remind.mp4",
  "reminder": "/Part1/Reminder.mp4",
  "remittance": "/Part1/Remittance.mp4",
  "remove": "/Part1/remove.mp4",
  "renewal": "/Part1/Renewal.mp4",
  "rent": "/Part1/Rent.mp4",
  "repair": "/Part1/repair.mp4",
  "repairer": "/Part1/Repairer.mp4",
  "repay": "/Part1/Repay.mp4",
  "reply": "/Part1/reply-1.mp4",
  "representation": "/Part1/Representation.mp4",
  "repulsive force": "/Part1/Repulsive Force.mp4",
  "repurchase": "/Part1/Repurchase.mp4",
  "requirement": "/Part1/Requirement.mp4",
  "requisite": "/Part1/Requisite.mp4",
  "reservation": "/Part1/Reservation.mp4",
  "residence": "/Part1/Residence.mp4",
  "resignation": "/Part1/Resignation.mp4",
  "resistor": "/Part1/Resistor-1.mp4",
  "resolution": "/Part1/Resolution.mp4",
  "resonance": "/Part1/Resonance.mp4",
  "resources": "/Part1/Resources.mp4",
  "respect": "/Part1/respect.mp4",
  "responsibility": "/Part1/Responsibility.mp4",
  "responsible": "/Part1/responsible.mp4",
  "rest": "/Part1/Rest.mp4",
  "restaurant": "/Part1/restaurant.mp4",
  "restore": "/Part1/Restore.mp4",
  "restricted": "/Part1/Restricted.mp4",
  "result": "/Part1/result-1.mp4",
  "resume": "/Part1/Resume.mp4",
  "retail": "/Part1/Retail.mp4",
  "retain": "/Part1/Retain.mp4",
  "retire": "/Part1/Retire.mp4",
  "retum lnward": "/Part1/Retum Lnward.mp4",
  "retum outward": "/Part1/Retum Outward.mp4",
  "return": "/Part1/return.mp4",
  "revalidation": "/Part1/Revalidation.mp4",
  "reversible": "/Part1/Reversible.mp4",
  "review": "/Part1/Review.mp4",
  "revised": "/Part1/Revised.mp4",
  "revolution": "/Part1/Revolution.mp4",
  "revolve": "/Part1/revolve.mp4",
  "reward": "/Part1/Reward.mp4",
  "rf osciilator": "/Part1/Rf Osciilator.mp4",
  "rhino": "/Part1/rhino.mp4",
  "rhinocerous": "/Part1/rhinocerous.mp4",
  "rhythmic": "/Part1/Rhythmic.mp4",
  "rice": "/Part1/rice-1.mp4",
  "rich": "/Part1/rich.mp4",
  "ride": "/Part1/ride.mp4",
  "right": "/Part1/right.mp4",
  "rigid": "/Part1/Rigid.mp4",
  "ring": "/Part1/ring.mp4",
  "riots": "/Part1/riots.mp4",
  "ripe": "/Part1/ripe.mp4",
  "risk": "/Part1/Risk.mp4",
  "river": "/Part1/river.mp4",
  "road": "/Part1/road.mp4",
  "roam": "/Part1/roam.mp4",
  "roar": "/Part1/roar.mp4",
  "rock": "/Part1/rock.mp4",
  "rocket": "/Part1/rocket.mp4",
  "roll": "/Part1/roll.mp4",
  "roof": "/Part1/roof.mp4",
  "room": "/Part1/room.mp4",
  "rose": "/Part1/rose.mp4",
  "rotate": "/Part1/rotate.mp4",
  "rotational motion": "/Part1/Rotational Motion.mp4",
  "rotational": "/Part1/Rotational.mp4",
  "rotten": "/Part1/rotten.mp4",
  "rough": "/Part1/rough.mp4",
  "round": "/Part1/Round.mp4",
  "routine": "/Part1/Routine.mp4",
  "rubber": "/Part1/rubber-1.mp4",
  "rule": "/Part1/rule.mp4",
  "ruler": "/Part1/ruler.mp4",
  "run": "/Part1/run.mp4",
  "running account": "/Part1/Running Account.mp4",
  "rural development": "/Part1/Rural Development.mp4",
  "rural oriented": "/Part1/Rural Oriented.mp4",
  "rural welfare": "/Part1/Rural Welfare.mp4",
  "rural": "/Part1/Rural.mp4",
  "russia": "/Part1/russia.mp4",
  "s i unit": "/Part1/S.I Unit.mp4",
  "sad": "/Part1/sad.mp4",
  "safe guard": "/Part1/Safe Guard.mp4",
  "sailor": "/Part1/sailor.mp4",
  "salary": "/Part1/Salary.mp4",
  "sales retum": "/Part1/Sales Retum.mp4",
  "saloon": "/Part1/saloon.mp4",
  "salt": "/Part1/salt.mp4",
  "salwar kameez": "/Part1/salwar kameez.mp4",
  "same": "/Part1/same.mp4",
  "sample": "/Part1/Sample.mp4",
  "sanction": "/Part1/Sanction.mp4",
  "sand": "/Part1/sand.mp4",
  "sandwitch": "/Part1/sandwitch.mp4",
  "sanks": "/Part1/sanks.mp4",
  "sari": "/Part1/sari.mp4",
  "satellites": "/Part1/Satellites.mp4",
  "satisfactory": "/Part1/Satisfactory.mp4",
  "satisfied": "/Part1/satisfied.mp4",
  "saturday": "/Part1/saturday-1.mp4",
  "saturn": "/Part1/Saturn.mp4",
  "saw": "/Part1/saw.mp4",
  "scales of pay": "/Part1/Scales (Of Pay).mp4",
  "scales": "/Part1/scales.mp4",
  "scent": "/Part1/scent.mp4",
  "scheduled caste sc": "/Part1/Scheduled Caste (Sc).mp4",
  "scheduled tribe st": "/Part1/Scheduled Tribe (St).mp4",
  "schematic": "/Part1/Schematic.mp4",
  "school bag": "/Part1/school bag.mp4",
  "school bus": "/Part1/school bus.mp4",
  "school": "/Part1/school.mp4",
  "scinece": "/Part1/scinece.mp4",
  "scissors": "/Part1/scissors.mp4",
  "scold": "/Part1/scold.mp4",
  "scooter": "/Part1/scooter.mp4",
  "scope": "/Part1/Scope.mp4",
  "screw guage": "/Part1/Screw Guage.mp4",
  "scribe": "/Part1/Scribe.mp4",
  "script": "/Part1/Script.mp4",
  "sculpture": "/Part1/sculpture.mp4",
  "sea": "/Part1/sea.mp4",
  "seal": "/Part1/Seal.mp4",
  "search": "/Part1/search.mp4",
  "season": "/Part1/season.mp4",
  "seat": "/Part1/seat.mp4",
  "second": "/Part1/Second.mp4",
  "secondary": "/Part1/Secondary.mp4",
  "seconds": "/Part1/seconds.mp4",
  "sector": "/Part1/Sector.mp4",
  "security collateral": "/Part1/Security Collateral.mp4",
  "security continuing": "/Part1/Security Continuing.mp4",
  "security convertible": "/Part1/Security Convertible.mp4",
  "security": "/Part1/Security.mp4",
  "see": "/Part1/see.mp4",
  "seed": "/Part1/seed.mp4",
  "seizure": "/Part1/Seizure.mp4",
  "selection grade": "/Part1/Selection Grade.mp4",
  "selective": "/Part1/Selective.mp4",
  "self balancing sign 1": "/Part1/Self Balancing(Sign-1).mp4",
  "self balancing sign 2": "/Part1/Self Balancing(Sign-2).mp4",
  "self employed": "/Part1/Self Employed.mp4",
  "self explanatory": "/Part1/Self Explanatory.mp4",
  "self help and self surrender": "/Part1/Self help and Self surrender.mp4",
  "self help": "/Part1/self help_1_FAC142479E964E34AD7F.mp4",
  "self": "/Part1/self.mp4",
  "selfish": "/Part1/selfish.mp4",
  "sell": "/Part1/sell.mp4",
  "semi solld": "/Part1/Semi Solld.mp4",
  "semi urban": "/Part1/Semi Urban.mp4",
  "send": "/Part1/send.mp4",
  "seniority": "/Part1/Seniority.mp4",
  "sentence": "/Part1/sentence.mp4",
  "separate": "/Part1/separate.mp4",
  "september": "/Part1/september-1.mp4",
  "series circuit": "/Part1/Series Circuit.mp4",
  "servant": "/Part1/servant.mp4",
  "serve": "/Part1/serve.mp4",
  "service": "/Part1/Service.mp4",
  "settle": "/Part1/Settle.mp4",
  "severally": "/Part1/Severally.mp4",
  "sewing machine": "/Part1/sewing machine.mp4",
  "shake": "/Part1/shake.mp4",
  "shappels": "/Part1/shappels-1.mp4",
  "sharbat": "/Part1/sharbat.mp4",
  "share capital": "/Part1/Share Capital.mp4",
  "share equity": "/Part1/Share Equity.mp4",
  "share holder": "/Part1/Share Holder.mp4",
  "share market": "/Part1/Share Market.mp4",
  "share preference": "/Part1/Share Preference.mp4",
  "share": "/Part1/share.mp4",
  "shares redeemable": "/Part1/Shares Redeemable.mp4",
  "sharpener": "/Part1/sharpener.mp4",
  "shave": "/Part1/shave.mp4",
  "she": "/Part1/she.mp4",
  "sheep": "/Part1/sheep.mp4",
  "sheet charge": "/Part1/Sheet Charge.mp4",
  "shift": "/Part1/Shift.mp4",
  "shine": "/Part1/shine.mp4",
  "ship": "/Part1/ship.mp4",
  "shipping freight": "/Part1/Shipping Freight.mp4",
  "shipping order": "/Part1/Shipping Order.mp4",
  "shirt": "/Part1/shirt.mp4",
  "shiva": "/Part1/shiva.mp4",
  "shoe": "/Part1/shoe.mp4",
  "shooting": "/Part1/shooting.mp4",
  "shop": "/Part1/shop-1.mp4",
  "shopkeeper": "/Part1/shopkeeper.mp4",
  "short": "/Part1/short.mp4",
  "shortage": "/Part1/Shortage.mp4",
  "shoulder": "/Part1/shoulder.mp4",
  "shout": "/Part1/shout.mp4",
  "show cause": "/Part1/Show Cause.mp4",
  "show": "/Part1/show.mp4",
  "shy": "/Part1/shy.mp4",
  "sick unit": "/Part1/Sick Unit.mp4",
  "sick": "/Part1/sick-1.mp4",
  "sight bill": "/Part1/Sight Bill.mp4",
  "signal": "/Part1/signal.mp4",
  "signatory": "/Part1/Signatory.mp4",
  "signature": "/Part1/Signature.mp4",
  "sikh": "/Part1/sikh-1.mp4",
  "silk": "/Part1/silk-1.mp4",
  "silver": "/Part1/silver.mp4",
  "simla": "/Part1/simla.mp4",
  "simpic mieroecope": "/Part1/Simpic  Mieroecope.mp4",
  "simultaneous": "/Part1/Simultaneous.mp4",
  "sing": "/Part1/sing.mp4",
  "singapore": "/Part1/singapore-1.mp4",
  "single entry": "/Part1/Single Entry.mp4",
  "single handed": "/Part1/single handed.mp4",
  "single owner": "/Part1/Single Owner.mp4",
  "sink": "/Part1/Sink.mp4",
  "sister in law": "/Part1/sister-in-law.mp4",
  "sister": "/Part1/sister.mp4",
  "sit": "/Part1/sit.mp4",
  "sitar": "/Part1/sitar.mp4",
  "site": "/Part1/Site.mp4",
  "six monthly": "/Part1/Six Monthly.mp4",
  "size": "/Part1/Size.mp4",
  "skilled labour": "/Part1/Skilled Labour.mp4",
  "skin": "/Part1/skin.mp4",
  "skip": "/Part1/skip.mp4",
  "skirt": "/Part1/skirt.mp4",
  "sky": "/Part1/sky.mp4",
  "sleep": "/Part1/sleep.mp4",
  "slim": "/Part1/slim.mp4",
  "slip": "/Part1/slip.mp4",
  "slow": "/Part1/slow.mp4",
  "slower": "/Part1/Slower.mp4",
  "sly": "/Part1/sly.mp4",
  "small coin depot": "/Part1/Small Coin Depot.mp4",
  "small enterprise": "/Part1/Small Enterprise.mp4",
  "small farmer": "/Part1/Small Farmer.mp4",
  "small pox": "/Part1/small pox.mp4",
  "small": "/Part1/small.mp4",
  "smell": "/Part1/smell.mp4",
  "smile": "/Part1/smile.mp4",
  "smooth": "/Part1/smooth.mp4",
  "snake": "/Part1/snake.mp4",
  "snow": "/Part1/snow.mp4",
  "soap": "/Part1/soap.mp4",
  "social society": "/Part1/Social Society.mp4",
  "society co operative": "/Part1/Society Co - Operative.mp4",
  "society marketing": "/Part1/Society Marketing.mp4",
  "socks": "/Part1/socks-1.mp4",
  "sofa": "/Part1/sofa.mp4",
  "sofe": "/Part1/sofe.mp4",
  "soft": "/Part1/soft.mp4",
  "soiar energy": "/Part1/Soiar Energy.mp4",
  "soidering fiux": "/Part1/Soidering Fiux.mp4",
  "soidering iron": "/Part1/Soidering Iron.mp4",
  "soidering lead": "/Part1/Soidering Lead.mp4",
  "soiled note": "/Part1/Soiled Note.mp4",
  "solar eclipse": "/Part1/Solar Eclipse.mp4",
  "solar system": "/Part1/Solar System.mp4",
  "soldier": "/Part1/soldier.mp4",
  "solicitor": "/Part1/Solicitor.mp4",
  "solid": "/Part1/solid.mp4",
  "solld fueis": "/Part1/Solld Fueis.mp4",
  "solld": "/Part1/Solld.mp4",
  "solve": "/Part1/solve.mp4",
  "some": "/Part1/some.mp4",
  "sometimes": "/Part1/sometimes.mp4",
  "son": "/Part1/son.mp4",
  "sorry": "/Part1/sorry.mp4",
  "sotar": "/Part1/Sotar.mp4",
  "soul": "/Part1/soul.mp4",
  "sound": "/Part1/Sound.mp4",
  "source": "/Part1/Source.mp4",
  "south america": "/Part1/south america.mp4",
  "south poie": "/Part1/South Poie.mp4",
  "south pole": "/Part1/South Pole.mp4",
  "south": "/Part1/South.mp4",
  "southern hemisphere": "/Part1/Southern Hemisphere.mp4",
  "sow": "/Part1/sow.mp4",
  "space": "/Part1/Space.mp4",
  "spanner": "/Part1/spanner.mp4",
  "sparrow": "/Part1/sparrow.mp4",
  "spastic": "/Part1/spastic.mp4",
  "special": "/Part1/special.mp4",
  "specific": "/Part1/Specific.mp4",
  "specimen signature": "/Part1/Specimen Signature.mp4",
  "specimen": "/Part1/Specimen.mp4",
  "speclfic heat": "/Part1/Speclfic Heat.mp4",
  "spectrometer": "/Part1/Spectrometer.mp4",
  "spectrum": "/Part1/Spectrum.mp4",
  "speech therapist": "/Part1/speech therapist.mp4",
  "speed": "/Part1/Speed.mp4",
  "spend": "/Part1/spend.mp4",
  "spendthrift": "/Part1/spendthrift.mp4",
  "sphere": "/Part1/Sphere.mp4",
  "sphoerical mirror": "/Part1/Sphoerical Mirror.mp4",
  "spider": "/Part1/spider.mp4",
  "spill": "/Part1/spill.mp4",
  "spilt": "/Part1/Spilt.mp4",
  "spiral": "/Part1/Spiral.mp4",
  "spoill": "/Part1/spoill-1.mp4",
  "sponsor": "/Part1/Sponsor.mp4",
  "spoon": "/Part1/spoon.mp4",
  "sports": "/Part1/sports.mp4",
  "spot and forward": "/Part1/Spot And Forward.mp4",
  "spot enchange": "/Part1/Spot Enchange.mp4",
  "spot price": "/Part1/Spot Price.mp4",
  "spot": "/Part1/Spot.mp4",
  "spring": "/Part1/Spring.mp4",
  "square": "/Part1/Square.mp4",
  "squeeze": "/Part1/squeeze.mp4",
  "squrriel": "/Part1/squrriel-1.mp4",
  "sri lanka": "/Part1/sri lanka.mp4",
  "stabilisation": "/Part1/Stabilisation.mp4",
  "staff": "/Part1/Staff.mp4",
  "stage": "/Part1/stage.mp4",
  "stamp": "/Part1/stamp.mp4",
  "stand": "/Part1/stand.mp4",
  "standard instructions si": "/Part1/Standard Instructions (Si).mp4",
  "standard": "/Part1/Standard.mp4",
  "stapdoun transformer": "/Part1/Stapdoun Transformer.mp4",
  "star": "/Part1/Star.mp4",
  "stars": "/Part1/stars.mp4",
  "start": "/Part1/start-1.mp4",
  "state": "/Part1/state.mp4",
  "statement of account": "/Part1/Statement Of Account.mp4",
  "statement of liquidation": "/Part1/Statement Of Liquidation.mp4",
  "statement": "/Part1/Statement.mp4",
  "static electricity": "/Part1/Static Electricity.mp4",
  "stationery": "/Part1/Stationery.mp4",
  "statlonary wave": "/Part1/Statlonary Wave.mp4",
  "status": "/Part1/Status.mp4",
  "stay": "/Part1/stay.mp4",
  "std": "/Part1/std.mp4",
  "stearn engine": "/Part1/Stearn Engine.mp4",
  "steel": "/Part1/steel.mp4",
  "stequp trans formor": "/Part1/Stequp Trans Formor.mp4",
  "stick": "/Part1/stick.mp4",
  "stingy": "/Part1/stingy.mp4",
  "stir": "/Part1/stir.mp4",
  "stitch": "/Part1/stitch.mp4",
  "stock book": "/Part1/Stock Book.mp4",
  "stock closing": "/Part1/Stock Closing.mp4",
  "stock in hand": "/Part1/Stock In Hand.mp4",
  "stock opening": "/Part1/Stock Opening.mp4",
  "stock": "/Part1/Stock.mp4",
  "stone": "/Part1/stone.mp4",
  "stop": "/Part1/stop.mp4",
  "storage": "/Part1/Storage.mp4",
  "store": "/Part1/store.mp4",
  "storm": "/Part1/storm.mp4",
  "story": "/Part1/story-1.mp4",
  "stove": "/Part1/stove.mp4",
  "straight forward": "/Part1/straight forward.mp4",
  "straight": "/Part1/Straight.mp4",
  "strength is the test": "/Part1/Strength is the Test.mp4",
  "strength": "/Part1/Strength.mp4",
  "stretch": "/Part1/Stretch.mp4",
  "strike": "/Part1/strike.mp4",
  "strong thing": "/Part1/strong (thing).mp4",
  "strong room": "/Part1/Strong Room.mp4",
  "strong": "/Part1/strong.mp4",
  "stubborn": "/Part1/stubborn.mp4",
  "student": "/Part1/student.mp4",
  "study": "/Part1/study.mp4",
  "sub division": "/Part1/Sub Division.mp4",
  "sub head": "/Part1/Sub Head.mp4",
  "sub lease": "/Part1/Sub Lease.mp4",
  "subject matter": "/Part1/Subject Matter.mp4",
  "submission": "/Part1/Submission.mp4",
  "subordinate": "/Part1/Subordinate.mp4",
  "subscription": "/Part1/Subscription.mp4",
  "subsidy sign 2": "/Part1/Subsidy (Sign -2).mp4",
  "subsidy sign 1": "/Part1/Subsidy(Sign-1).mp4",
  "subtract": "/Part1/subtract.mp4",
  "succession": "/Part1/Succession.mp4",
  "such is the pride money begets": "/Part1/Such is the Pride Money Begets.mp4",
  "sue": "/Part1/Sue.mp4",
  "sufficient": "/Part1/Sufficient.mp4",
  "sugar": "/Part1/sugar-1.mp4",
  "sugarcane": "/Part1/sugarcane.mp4",
  "sum": "/Part1/Sum.mp4",
  "summons": "/Part1/Summons.mp4",
  "sun": "/Part1/Sun.mp4",
  "sunday": "/Part1/sunday-1.mp4",
  "sundry creditors": "/Part1/Sundry Creditors.mp4",
  "sundry debtors": "/Part1/Sundry Debtors.mp4",
  "sundry": "/Part1/Sundry.mp4",
  "sunflower": "/Part1/sunflower.mp4",
  "sunlight": "/Part1/Sunlight.mp4",
  "sunrise": "/Part1/sunrise.mp4",
  "sunset": "/Part1/sunset.mp4",
  "super annuation": "/Part1/Super - Annuation.mp4",
  "superposltion": "/Part1/Superposltion.mp4",
  "supersession": "/Part1/Supersession.mp4",
  "supervision": "/Part1/Supervision.mp4",
  "supplementary": "/Part1/Supplementary.mp4",
  "supply": "/Part1/supply.mp4",
  "surat": "/Part1/surat.mp4",
  "surcharge": "/Part1/Surcharge.mp4",
  "surety": "/Part1/Surety.mp4",
  "surgeon": "/Part1/surgeon.mp4",
  "surname": "/Part1/surname.mp4",
  "surplus": "/Part1/Surplus.mp4",
  "surprise": "/Part1/surprise.mp4",
  "surrender": "/Part1/Surrender.mp4",
  "surrounding": "/Part1/Surrounding.mp4",
  "survey": "/Part1/Survey.mp4",
  "survivorship": "/Part1/Survivorship.mp4",
  "suspect": "/Part1/suspect.mp4",
  "suspend payment": "/Part1/Suspend Payment.mp4",
  "suspend": "/Part1/Suspend.mp4",
  "swallow": "/Part1/swallow.mp4",
  "sweat": "/Part1/sweat.mp4",
  "sweater": "/Part1/sweater.mp4",
  "sweep": "/Part1/sweep.mp4",
  "sweet": "/Part1/sweet-1.mp4",
  "sweetlime": "/Part1/sweetlime.mp4",
  "sweets": "/Part1/sweets.mp4",
  "swim": "/Part1/swim.mp4",
  "swing": "/Part1/swing.mp4",
  "switch": "/Part1/Switch.mp4",
  "symbol": "/Part1/Symbol.mp4",
  "syndication": "/Part1/Syndication.mp4",
  "tabala": "/Part1/tabala.mp4",
  "table tennis": "/Part1/table tennis.mp4",
  "table": "/Part1/table.mp4",
  "tablet": "/Part1/tablet.mp4",
  "tail": "/Part1/tail.mp4",
  "tailer": "/Part1/tailer.mp4",
  "take home pay": "/Part1/Take Home Pay.mp4",
  "take over": "/Part1/Take Over.mp4",
  "take": "/Part1/take.mp4",
  "talk": "/Part1/talk.mp4",
  "tall": "/Part1/tall.mp4",
  "tally": "/Part1/Tally.mp4",
  "taluk": "/Part1/taluk.mp4",
  "tamil nadu": "/Part1/tamil nadu.mp4",
  "tamil": "/Part1/tamil.mp4",
  "target": "/Part1/Target.mp4",
  "tariff": "/Part1/Tariff.mp4",
  "tarreca": "/Part1/tarreca.mp4",
  "task force": "/Part1/Task Force.mp4",
  "task wage": "/Part1/Task Wage.mp4",
  "taste": "/Part1/taste.mp4",
  "tax exemption": "/Part1/Tax Exemption.mp4",
  "tax profession": "/Part1/Tax Profession.mp4",
  "tax property": "/Part1/Tax Property.mp4",
  "tax": "/Part1/Tax.mp4",
  "taxable": "/Part1/Taxable.mp4",
  "taxi": "/Part1/taxi.mp4",
  "tea": "/Part1/tea.mp4",
  "teach": "/Part1/teach.mp4",
  "teacher": "/Part1/teacher.mp4",
  "tear sheet": "/Part1/Tear Sheet.mp4",
  "tear": "/Part1/tear.mp4",
  "tease": "/Part1/tease.mp4",
  "technoiogy": "/Part1/Technoiogy.mp4",
  "teeth": "/Part1/teeth.mp4",
  "telegram": "/Part1/telegram.mp4",
  "telephone": "/Part1/Telephone.mp4",
  "telescope": "/Part1/Telescope.mp4",
  "television": "/Part1/Television.mp4",
  "telgu": "/Part1/telgu.mp4",
  "tell": "/Part1/tell.mp4",
  "teller": "/Part1/Teller.mp4",
  "temperature": "/Part1/Temperature.mp4",
  "temple": "/Part1/temple.mp4",
  "temporary": "/Part1/temporary.mp4",
  "tenancy": "/Part1/Tenancy.mp4",
  "tender": "/Part1/Tender.mp4",
  "tennis": "/Part1/tennis.mp4",
  "term of office": "/Part1/Term Of Office.mp4",
  "term technical": "/Part1/Term Technical.mp4",
  "terminate": "/Part1/Terminate.mp4",
  "terms of service": "/Part1/Terms Of Service.mp4",
  "terrace": "/Part1/terrace.mp4",
  "territorial": "/Part1/Territorial.mp4",
  "testament": "/Part1/Testament.mp4",
  "testify": "/Part1/Testify.mp4",
  "thank you": "/Part1/Thank You.mp4",
  "that": "/Part1/that.mp4",
  "their": "/Part1/their.mp4",
  "them": "/Part1/them.mp4",
  "themselves": "/Part1/themselves.mp4",
  "then": "/Part1/then.mp4",
  "there": "/Part1/there.mp4",
  "thermal energy": "/Part1/Thermal Energy.mp4",
  "thermal": "/Part1/Thermal.mp4",
  "thermometer": "/Part1/Thermometer.mp4",
  "thermostat": "/Part1/Thermostat.mp4",
  "these": "/Part1/these.mp4",
  "they": "/Part1/they.mp4",
  "thick": "/Part1/thick.mp4",
  "thief": "/Part1/thief-1.mp4",
  "thigh": "/Part1/thigh.mp4",
  "thin": "/Part1/thin.mp4",
  "things": "/Part1/things.mp4",
  "think": "/Part1/think.mp4",
  "third party": "/Part1/Third Party.mp4",
  "thirsty": "/Part1/thirsty.mp4",
  "this": "/Part1/this.mp4",
  "thorn": "/Part1/thorn.mp4",
  "those": "/Part1/those.mp4",
  "thread": "/Part1/thread.mp4",
  "thriff": "/Part1/Thriff.mp4",
  "throat": "/Part1/throat.mp4",
  "through": "/Part1/through.mp4",
  "throw": "/Part1/throw.mp4",
  "thumb impression": "/Part1/Thumb Impression.mp4",
  "thunder": "/Part1/thunder.mp4",
  "thursday": "/Part1/thursday-1.mp4",
  "ticket checker": "/Part1/ticket checker.mp4",
  "ticket": "/Part1/ticket.mp4",
  "tie": "/Part1/tie.mp4",
  "tiffin box": "/Part1/tiffin box.mp4",
  "tiger": "/Part1/tiger.mp4",
  "tight": "/Part1/tight.mp4",
  "tiller": "/Part1/Tiller.mp4",
  "time bound": "/Part1/Time Bound.mp4",
  "time limit": "/Part1/Time Limit.mp4",
  "time": "/Part1/time.mp4",
  "tired": "/Part1/tired.mp4",
  "title": "/Part1/Title.mp4",
  "tldal energy": "/Part1/Tldal Energy.mp4",
  "to": "/Part1/to.mp4",
  "toast": "/Part1/toast.mp4",
  "today": "/Part1/today.mp4",
  "toes": "/Part1/toes.mp4",
  "toilet": "/Part1/toilet-1.mp4",
  "tomato": "/Part1/tomato.mp4",
  "tomorrow": "/Part1/tomorrow.mp4",
  "tongs": "/Part1/tongs.mp4",
  "tongue": "/Part1/tongue.mp4",
  "tonic": "/Part1/tonic.mp4",
  "tools": "/Part1/tools.mp4",
  "toothbrush": "/Part1/toothbrush.mp4",
  "toothpaste": "/Part1/toothpaste.mp4",
  "top management": "/Part1/Top Management.mp4",
  "torch": "/Part1/torch.mp4",
  "tortoise": "/Part1/tortoise-1.mp4",
  "total energy": "/Part1/Total Energy.mp4",
  "total": "/Part1/Total.mp4",
  "touch f135": "/Part1/touch.f135.mp4",
  "tour": "/Part1/Tour.mp4",
  "towards": "/Part1/towards.mp4",
  "towel": "/Part1/towel.mp4",
  "town": "/Part1/town.mp4",
  "track": "/Part1/track.mp4",
  "trade discount": "/Part1/Trade Discount.mp4",
  "trade": "/Part1/trade.mp4",
  "train": "/Part1/train-2.mp4",
  "training": "/Part1/Training.mp4",
  "transaction": "/Part1/Transaction.mp4",
  "transcription": "/Part1/Transcription.mp4",
  "transfer": "/Part1/Transfer.mp4",
  "transformation of energy": "/Part1/Transformation Of Energy.mp4",
  "transformer": "/Part1/Transformer.mp4",
  "transister": "/Part1/Transister.mp4",
  "translation of motion": "/Part1/Translation Of Motion.mp4",
  "transparent": "/Part1/transparent.mp4",
  "transport": "/Part1/Transport.mp4",
  "travel": "/Part1/Travel.mp4",
  "treasury": "/Part1/Treasury.mp4",
  "tree": "/Part1/tree.mp4",
  "trial balance": "/Part1/Trial Balance.mp4",
  "triangle": "/Part1/Triangle.mp4",
  "tribal": "/Part1/Tribal.mp4",
  "tribunal": "/Part1/Tribunal.mp4",
  "triode": "/Part1/Triode.mp4",
  "trivendrum": "/Part1/trivendrum.mp4",
  "trophy": "/Part1/trophy.mp4",
  "trouble": "/Part1/trouble-1.mp4",
  "troughs": "/Part1/Troughs.mp4",
  "trregutar vibration": "/Part1/Trregutar Vibration.mp4",
  "true copy": "/Part1/True Copy.mp4",
  "true": "/Part1/true.mp4",
  "trunk": "/Part1/trunk.mp4",
  "trunsverse wave": "/Part1/Trunsverse Wave.mp4",
  "trust": "/Part1/trust.mp4",
  "trustee": "/Part1/Trustee.mp4",
  "trustworthiness": "/Part1/Trustworthiness.mp4",
  "try": "/Part1/try.mp4",
  "tubelight": "/Part1/tubelight.mp4",
  "tuberculosis": "/Part1/tuberculosis.mp4",
  "tuesday": "/Part1/tuesday-1.mp4",
  "tum over": "/Part1/Tum Over.mp4",
  "tunning fork": "/Part1/Tunning Fork.mp4",
  "turkey": "/Part1/turkey.mp4",
  "turn": "/Part1/turn.mp4",
  "turnout": "/Part1/Turnout.mp4",
  "tuseday": "/Part1/tuseday-2.mp4",
  "tusks": "/Part1/tusks.mp4",
  "tusts": "/Part1/tusts.mp4",
  "twins": "/Part1/twins.mp4",
  "typist": "/Part1/typist.mp4",
  "typwriter": "/Part1/typwriter.mp4",
  "ugly": "/Part1/ugly.mp4",
  "uitrasonic": "/Part1/Uitrasonic.mp4",
  "uitravioiet ray": "/Part1/Uitravioiet Ray.mp4",
  "umbrella": "/Part1/umbrella.mp4",
  "unanimous": "/Part1/Unanimous.mp4",
  "unauthorised": "/Part1/Unauthorised.mp4",
  "unavoidable": "/Part1/Unavoidable.mp4",
  "unbalance": "/Part1/Unbalance.mp4",
  "uncalled": "/Part1/Uncalled.mp4",
  "uncertainity": "/Part1/Uncertainity.mp4",
  "unclaimed": "/Part1/Unclaimed.mp4",
  "unconditional": "/Part1/Unconditional.mp4",
  "uncovered": "/Part1/Uncovered.mp4",
  "uncumbered": "/Part1/Uncumbered.mp4",
  "under consideration": "/Part1/Under Consideration.mp4",
  "under developed": "/Part1/Under Developed.mp4",
  "under mentioned": "/Part1/Under Mentioned.mp4",
  "under subscirbed": "/Part1/Under Subscirbed.mp4",
  "under valuation": "/Part1/Under Valuation.mp4",
  "under": "/Part1/under.mp4",
  "understand": "/Part1/understand-1.mp4",
  "undertaking": "/Part1/Undertaking.mp4",
  "underwriter": "/Part1/Underwriter.mp4",
  "undivided": "/Part1/Undivided.mp4",
  "unearned": "/Part1/Unearned.mp4",
  "unemployment": "/Part1/Unemployment.mp4",
  "unfit": "/Part1/Unfit.mp4",
  "uniform motion": "/Part1/Uniform Motion.mp4",
  "uniform": "/Part1/Uniform.mp4",
  "unifrom": "/Part1/unifrom.mp4",
  "union": "/Part1/Union.mp4",
  "unit": "/Part1/Unit.mp4",
  "united states of america": "/Part1/united states of america.mp4",
  "universe": "/Part1/Universe.mp4",
  "university": "/Part1/university.mp4",
  "unjapi": "/Part1/unjapi.mp4",
  "unlimited": "/Part1/Unlimited.mp4",
  "unlucky": "/Part1/unlucky.mp4",
  "unpaid": "/Part1/Unpaid.mp4",
  "unregistered": "/Part1/Unregistered.mp4",
  "until": "/Part1/until.mp4",
  "up": "/Part1/up.mp4",
  "upper age limit": "/Part1/Upper Age Limit.mp4",
  "upward": "/Part1/Upward.mp4",
  "uranus": "/Part1/Uranus.mp4",
  "urdu": "/Part1/urdu.mp4",
  "urgent": "/Part1/Urgent.mp4",
  "us": "/Part1/us.mp4",
  "uttar pradesh": "/Part1/uttar pradesh.mp4",
  "vacancy": "/Part1/Vacancy.mp4",
  "vacation": "/Part1/Vacation.mp4",
  "vaccum": "/Part1/Vaccum.mp4",
  "vada": "/Part1/vada.mp4",
  "vadodara": "/Part1/vadodara.mp4",
  "valid": "/Part1/Valid.mp4",
  "valley": "/Part1/valley.mp4",
  "valuable consideration": "/Part1/Valuable Consideration.mp4",
  "van": "/Part1/van.mp4",
  "vapour": "/Part1/vapour.mp4",
  "varaiable": "/Part1/Varaiable.mp4",
  "varanasi": "/Part1/varanasi.mp4",
  "variable": "/Part1/Variable.mp4",
  "variety": "/Part1/Variety.mp4",
  "vault safe deposit": "/Part1/Vault Safe Deposit.mp4",
  "vault": "/Part1/Vault.mp4",
  "vegetables": "/Part1/vegetables.mp4",
  "vegetarian": "/Part1/vegetarian.mp4",
  "vehicles": "/Part1/vehicles.mp4",
  "velocity": "/Part1/Velocity.mp4",
  "vendee": "/Part1/Vendee.mp4",
  "vendor": "/Part1/Vendor.mp4",
  "venus": "/Part1/Venus.mp4",
  "verdict": "/Part1/Verdict.mp4",
  "verification": "/Part1/Verification.mp4",
  "vernier caliper": "/Part1/Vernier Caliper.mp4",
  "versus": "/Part1/Versus.mp4",
  "vertical": "/Part1/Vertical.mp4",
  "vessel": "/Part1/vessel.mp4",
  "viatble ray": "/Part1/Viatble Ray.mp4",
  "vibgyor": "/Part1/Vibgyor.mp4",
  "vibration": "/Part1/Vibration.mp4",
  "vide": "/Part1/Vide.mp4",
  "video camera": "/Part1/Video Camera.mp4",
  "video cassette recorder": "/Part1/video cassette recorder.mp4",
  "vigilance": "/Part1/Vigilance.mp4",
  "village": "/Part1/village.mp4",
  "violet": "/Part1/Violet.mp4",
  "virtual image": "/Part1/Virtual Image.mp4",
  "visa": "/Part1/Visa.mp4",
  "vision": "/Part1/Vision.mp4",
  "visit": "/Part1/visit.mp4",
  "visitor": "/Part1/Visitor.mp4",
  "visual aid": "/Part1/Visual Aid.mp4",
  "vital": "/Part1/Vital.mp4",
  "voit": "/Part1/Voit.mp4",
  "voitmeter": "/Part1/Voitmeter.mp4",
  "volcano": "/Part1/Volcano.mp4",
  "volley ball": "/Part1/volley ball.mp4",
  "volume": "/Part1/Volume.mp4",
  "voluntarily": "/Part1/Voluntarily.mp4",
  "vomit": "/Part1/vomit.mp4",
  "vote": "/Part1/vote.mp4",
  "voucher": "/Part1/Voucher.mp4",
  "wage": "/Part1/Wage.mp4",
  "waist": "/Part1/waist.mp4",
  "wait": "/Part1/wait-1.mp4",
  "waiting list": "/Part1/Waiting List.mp4",
  "waive": "/Part1/Waive.mp4",
  "walk": "/Part1/walk.mp4",
  "want": "/Part1/want-1.mp4",
  "warehouse": "/Part1/Warehouse.mp4",
  "warm": "/Part1/warm.mp4",
  "warn": "/Part1/warn.mp4",
  "warning": "/Part1/Warning.mp4",
  "wash": "/Part1/wash.mp4",
  "washbasin": "/Part1/washbasin.mp4",
  "wastage": "/Part1/Wastage.mp4",
  "waste": "/Part1/waste.mp4",
  "watch": "/Part1/watch.mp4",
  "water bottle": "/Part1/water bottle.mp4",
  "water poltution": "/Part1/Water Poltution.mp4",
  "water": "/Part1/Water.mp4",
  "waterfall": "/Part1/waterfall.mp4",
  "watermelon": "/Part1/watermelon.mp4",
  "watt": "/Part1/Watt.mp4",
  "wattmeter": "/Part1/Wattmeter.mp4",
  "wave length": "/Part1/Wave Length.mp4",
  "wave": "/Part1/Wave.mp4",
  "wavegraph": "/Part1/Wavegraph.mp4",
  "wavemotion": "/Part1/Wavemotion.mp4",
  "waves": "/Part1/waves.mp4",
  "wax": "/Part1/Wax.mp4",
  "way": "/Part1/way.mp4",
  "we are like silkworms": "/Part1/We are like Silkworms.mp4",
  "we": "/Part1/we.mp4",
  "weak": "/Part1/weak-1.mp4",
  "wealth": "/Part1/Wealth.mp4",
  "wear": "/Part1/wear.mp4",
  "weaver": "/Part1/weaver.mp4",
  "wedding": "/Part1/wedding-1.mp4",
  "wednesday": "/Part1/wednesday-1.mp4",
  "week": "/Part1/week-1.mp4",
  "weekly return": "/Part1/Weekly Return.mp4",
  "weigh": "/Part1/weigh.mp4",
  "weight": "/Part1/Weight.mp4",
  "welcome": "/Part1/welcome.mp4",
  "welder": "/Part1/welder.mp4",
  "west bengal": "/Part1/west bengal.mp4",
  "west indies": "/Part1/west indies-1.mp4",
  "west": "/Part1/West-1.mp4",
  "wet": "/Part1/wet.mp4",
  "whale": "/Part1/whale.mp4",
  "what time": "/Part1/what time.mp4",
  "what": "/Part1/what.mp4",
  "wheat": "/Part1/wheat-1.mp4",
  "when all teeth fall": "/Part1/When All Teeth Fall.mp4",
  "when": "/Part1/when.mp4",
  "where": "/Part1/where.mp4",
  "which": "/Part1/which.mp4",
  "whistle": "/Part1/whistle.mp4",
  "white collar job": "/Part1/White Collar Job.mp4",
  "white": "/Part1/White.mp4",
  "who": "/Part1/Who.mp4",
  "wholesale": "/Part1/Wholesale.mp4",
  "whose": "/Part1/whose.mp4",
  "why we disagree": "/Part1/Why We Disagree.mp4",
  "why": "/Part1/why.mp4",
  "wide": "/Part1/wide.mp4",
  "wife": "/Part1/wife-1.mp4",
  "will": "/Part1/Will.mp4",
  "win": "/Part1/win.mp4",
  "wind energy": "/Part1/Wind Energy.mp4",
  "wind": "/Part1/Wind.mp4",
  "winding up": "/Part1/Winding Up.mp4",
  "window dressing": "/Part1/Window Dressing.mp4",
  "window": "/Part1/window.mp4",
  "wipe": "/Part1/wipe.mp4",
  "wire": "/Part1/Wire.mp4",
  "wish": "/Part1/wish.mp4",
  "with": "/Part1/with.mp4",
  "withdrawal slip": "/Part1/Withdrawal Slip.mp4",
  "withhold": "/Part1/Withhold.mp4",
  "without prejudice": "/Part1/Without Prejudice.mp4",
  "without": "/Part1/without.mp4",
  "witness": "/Part1/Witness.mp4",
  "wolf": "/Part1/wolf.mp4",
  "woman": "/Part1/woman.mp4",
  "wood": "/Part1/wood-1.mp4",
  "wool": "/Part1/wool.mp4",
  "word": "/Part1/word.mp4",
  "words and figures in": "/Part1/Words And Figures - In.mp4",
  "work": "/Part1/Work.mp4",
  "working capital": "/Part1/Working Capital.mp4",
  "working hours": "/Part1/Working Hours.mp4",
  "world wide": "/Part1/World - Wide.mp4",
  "world things": "/Part1/world things_1_AA015BD182CF4733877C.mp4",
  "world": "/Part1/world.mp4",
  "worry": "/Part1/worry.mp4",
  "worth": "/Part1/Worth.mp4",
  "wound": "/Part1/wound.mp4",
  "wrestling": "/Part1/wrestling.mp4",
  "writ": "/Part1/Writ.mp4",
  "write": "/Part1/write.mp4",
  "written down value": "/Part1/Written Down Value.mp4",
  "wrong": "/Part1/wrong.mp4",
  "x ray": "/Part1/X - Ray.mp4",
  "year accounting": "/Part1/Year - Accounting.mp4",
  "year book": "/Part1/Year Book.mp4",
  "year calender": "/Part1/Year Calender.mp4",
  "year financial": "/Part1/Year Financial.mp4",
  "year of harvest": "/Part1/Year Of Harvest.mp4",
  "year under report": "/Part1/Year Under Report.mp4",
  "year": "/Part1/Year.mp4",
  "yearly": "/Part1/Yearly.mp4",
  "yellow": "/Part1/yellow -1.mp4",
  "yesterday": "/Part1/yesterday.mp4",
  "you plural": "/Part1/you (plural).mp4",
  "you": "/Part1/you.mp4",
  "young": "/Part1/young.mp4",
  "your plural": "/Part1/your(plural).mp4",
  "your": "/Part1/your.mp4",
  "yourself": "/Part1/yourself.mp4",
  "zebra crossing": "/Part1/zebra crossing.mp4",
  "zebra": "/Part1/zebra.mp4",
  "zero correction": "/Part1/Zero Correction.mp4",
  "zero error": "/Part1/Zero Error.mp4",
  "zonal": "/Part1/Zonal.mp4",
  "zone": "/Part1/Zone.mp4",
  "zoo": "/Part1/zoo.mp4",
  "goods": "/Part2/Goods.mp4",
  "gossip": "/Part2/gossip.mp4",
  "government": "/Part2/government.mp4",
  "grain": "/Part2/grain.mp4",
  "gram": "/Part2/Gram.mp4",
  "granddaughter": "/Part2/granddaughter.mp4",
  "grandfather": "/Part2/grandfather.mp4",
  "grandmother": "/Part2/grandmother.mp4",
  "grandson": "/Part2/grandson.mp4",
  "grass": "/Part2/grass.mp4",
  "gravity": "/Part2/Gravity.mp4",
  "green": "/Part2/Green.mp4",
  "grey": "/Part2/Grey.mp4",
  "grind": "/Part2/grind.mp4",
  "gross": "/Part2/Gross.mp4",
  "groundnut": "/Part2/groundnut.mp4",
  "group": "/Part2/group.mp4",
  "grow": "/Part2/grow.mp4",
  "growth": "/Part2/Growth.mp4",
  "guard": "/Part2/guard.mp4",
  "guilty": "/Part2/guilty-1.mp4",
  "guitar": "/Part2/guitar.mp4",
  "gujarat": "/Part2/gujarat-1.mp4",
  "gujarati": "/Part2/gujarati.mp4",
  "gun": "/Part2/gun.mp4",
  "gurunanak jayanthi": "/Part2/gurunanak jayanthi.mp4",
  "guwahati": "/Part2/guwahati.mp4",
  "hair": "/Part2/hair.mp4",
  "half yearly": "/Part2/Half - Yearly.mp4",
  "halting allowance": "/Part2/Halting Allowance.mp4",
  "hammer": "/Part2/hammer.mp4",
  "hand": "/Part2/hand.mp4",
  "handicapped": "/Part2/handicapped.mp4",
  "handkerchief": "/Part2/handkerchief.mp4",
  "hang": "/Part2/hang-1.mp4",
  "hanuman": "/Part2/hanuman-1.mp4",
  "happy": "/Part2/happy.mp4",
  "harbour": "/Part2/harbour.mp4",
  "hard": "/Part2/hard-1.mp4",
  "hardworking": "/Part2/hardworking-1.mp4",
  "hariyana": "/Part2/hariyana.mp4",
  "harmonium": "/Part2/harmonium.mp4",
  "harvest": "/Part2/harvest.mp4",
  "hate": "/Part2/hate-1.mp4",
  "he": "/Part2/he.mp4",
  "head of income": "/Part2/Head Of Income.mp4",
  "head office": "/Part2/Head Office.mp4",
  "head": "/Part2/head.mp4",
  "health": "/Part2/health.mp4",
  "hear listen": "/Part2/hear-listen.mp4",
  "hear": "/Part2/hear.mp4",
  "hearing aid": "/Part2/hearing aid-1.mp4",
  "hearing": "/Part2/hearing.mp4",
  "heart": "/Part2/heart.mp4",
  "heat engine": "/Part2/Heat Engine.mp4",
  "heat": "/Part2/Heat.mp4",
  "heavier": "/Part2/Heavier.mp4",
  "heavy": "/Part2/heavy.mp4",
  "heir": "/Part2/Heir.mp4",
  "helicopter": "/Part2/helicopter.mp4",
  "help": "/Part2/help.mp4",
  "hemisphere": "/Part2/Hemisphere.mp4",
  "hen": "/Part2/hen.mp4",
  "her": "/Part2/her.mp4",
  "here": "/Part2/here.mp4",
  "hers": "/Part2/hers.mp4",
  "herself": "/Part2/herself.mp4",
  "hesrt": "/Part2/hesrt.mp4",
  "hexadecimal": "/Part2/Hexadecimal.mp4",
  "hide": "/Part2/hide.mp4",
  "high resistance": "/Part2/High Resistance.mp4",
  "high": "/Part2/high.mp4",
  "hill": "/Part2/hill.mp4",
  "him": "/Part2/him.mp4",
  "himachal pradesh": "/Part2/himachal pradesh.mp4",
  "himself": "/Part2/himself.mp4",
  "hindi": "/Part2/hindi.mp4",
  "hindu undivided family": "/Part2/Hindu Undivided Family.mp4",
  "hindu": "/Part2/hindu-1.mp4",
  "hip": "/Part2/hip.mp4",
  "hippo": "/Part2/hippo.mp4",
  "hire charges": "/Part2/Hire Charges.mp4",
  "hire qurchase": "/Part2/Hire Qurchase.mp4",
  "his": "/Part2/his.mp4",
  "history": "/Part2/history.mp4",
  "hoarding": "/Part2/Hoarding.mp4",
  "hockey": "/Part2/hockey.mp4",
  "hold": "/Part2/hold.mp4",
  "holder": "/Part2/Holder.mp4",
  "hole": "/Part2/hole.mp4",
  "holi": "/Part2/holi.mp4",
  "holiday": "/Part2/holiday.mp4",
  "hollow": "/Part2/hollow.mp4",
  "holy": "/Part2/holy.mp4",
  "home": "/Part2/home.mp4",
  "hop": "/Part2/hop.mp4",
  "hope": "/Part2/hope.mp4",
  "horizontal": "/Part2/Horizontal.mp4",
  "horns": "/Part2/horns.mp4",
  "horse cart": "/Part2/horse cart.mp4",
  "horse": "/Part2/horse.mp4",
  "hospital": "/Part2/hospital.mp4",
  "hot to feel": "/Part2/hot (to feel)-1.mp4",
  "hot to taste": "/Part2/hot (to taste).mp4",
  "hot to touch": "/Part2/hot (to touch).mp4",
  "hot": "/Part2/Hot.mp4",
  "hotel": "/Part2/hotel.mp4",
  "hour": "/Part2/Hour.mp4",
  "hours": "/Part2/hours.mp4",
  "hourse": "/Part2/hourse.mp4",
  "house": "/Part2/house.mp4",
  "housefly": "/Part2/housefly.mp4",
  "housing loan": "/Part2/Housing Loan.mp4",
  "how big": "/Part2/how big.mp4",
  "how many": "/Part2/how many.mp4",
  "how much": "/Part2/how much.mp4",
  "how": "/Part2/how.mp4",
  "huid pressure": "/Part2/Huid Pressure.mp4",
  "humldlty": "/Part2/Humldlty.mp4",
  "hungry": "/Part2/hungry.mp4",
  "hurt": "/Part2/hurt.mp4",
  "husband": "/Part2/husband-1.mp4",
  "hut": "/Part2/hut.mp4",
  "hyderabad": "/Part2/hyderabad.mp4",
  "hydrautic press": "/Part2/Hydrautic Press.mp4",
  "hydro electricity": "/Part2/Hydro Electricity.mp4",
  "hydro energy": "/Part2/Hydro Energy.mp4",
  "hydroiogy": "/Part2/Hydroiogy.mp4",
  "hypothecated": "/Part2/Hypothecated.mp4",
  "i": "/Part2/I.mp4",
  "ice cream": "/Part2/ice cream.mp4",
  "idd": "/Part2/idd.mp4",
  "identification": "/Part2/Identification.mp4",
  "iiiiterate": "/Part2/iiiiterate.mp4",
  "illegal": "/Part2/Illegal.mp4",
  "immediate": "/Part2/Immediate.mp4",
  "immiscibility": "/Part2/Immiscibility.mp4",
  "immovable property": "/Part2/Immovable Property.mp4",
  "implementation": "/Part2/Implementation.mp4",
  "import": "/Part2/Import.mp4",
  "important": "/Part2/Important.mp4",
  "improve": "/Part2/improve.mp4",
  "improvement": "/Part2/Improvement.mp4",
  "in advance": "/Part2/In Advance.mp4",
  "in front of": "/Part2/in front of.mp4",
  "in lieu of": "/Part2/In Lieu Of.mp4",
  "in multiples of": "/Part2/In Multiples Of.mp4",
  "in": "/Part2/in.mp4",
  "inauguaration": "/Part2/Inauguaration.mp4",
  "incentive": "/Part2/Incentive.mp4",
  "inch": "/Part2/inch.mp4",
  "incharge": "/Part2/Incharge.mp4",
  "income tax": "/Part2/Income Tax.mp4",
  "income": "/Part2/Income.mp4",
  "incompetence": "/Part2/Incompetence.mp4",
  "increase": "/Part2/Increase.mp4",
  "independent": "/Part2/Independent.mp4",
  "index": "/Part2/Index.mp4",
  "india": "/Part2/india-1.mp4",
  "indigo": "/Part2/Indigo.mp4",
  "individual": "/Part2/Individual.mp4",
  "indorsement": "/Part2/Indorsement.mp4",
  "inductor": "/Part2/Inductor.mp4",
  "industry cottage": "/Part2/Industry - Cottage.mp4",
  "industry large scale": "/Part2/Industry - Large Scale.mp4",
  "industry small scale": "/Part2/Industry - Small Scale.mp4",
  "inefficient": "/Part2/Inefficient.mp4",
  "inelastic": "/Part2/Inelastic.mp4",
  "infinity": "/Part2/Infinity.mp4",
  "information": "/Part2/Information.mp4",
  "infrared ray": "/Part2/Infrared Ray.mp4",
  "infrasonic": "/Part2/Infrasonic.mp4",
  "initial": "/Part2/Initial.mp4",
  "initials": "/Part2/Initials.mp4",
  "injection": "/Part2/injection.mp4",
  "input": "/Part2/Input.mp4",
  "inspection": "/Part2/Inspection.mp4",
  "installation": "/Part2/Installation.mp4",
  "instalment": "/Part2/Instalment.mp4",
  "instigate": "/Part2/instigate.mp4",
  "institute": "/Part2/Institute.mp4",
  "instruction": "/Part2/Instruction.mp4",
  "instrument": "/Part2/Instrument.mp4",
  "instument negotiable": "/Part2/Instument - Negotiable.mp4",
  "insult": "/Part2/insult-1.mp4",
  "insurance": "/Part2/Insurance.mp4",
  "intcnetly": "/Part2/Intcnetly.mp4",
  "intemal": "/Part2/Intemal.mp4",
  "intensive": "/Part2/Intensive.mp4",
  "inter branch transaction": "/Part2/Inter Branch Transaction.mp4",
  "interest compound": "/Part2/Interest - Compound.mp4",
  "interest rate": "/Part2/Interest - Rate.mp4",
  "interest simple": "/Part2/Interest Simple.mp4",
  "interest": "/Part2/interest-1.mp4",
  "interfere": "/Part2/interfere.mp4",
  "interference": "/Part2/Interference.mp4",
  "intergrated chip": "/Part2/Intergrated Chip.mp4",
  "intermal combustion engine": "/Part2/Intermal Combustion Engine.mp4",
  "intermediate": "/Part2/Intermediate.mp4",
  "internal": "/Part2/Internal.mp4",
  "interrogation": "/Part2/Interrogation.mp4",
  "interruption": "/Part2/Interruption.mp4",
  "interval": "/Part2/Interval.mp4",
  "interview": "/Part2/Interview.mp4",
  "introduce": "/Part2/introduce.mp4",
  "introduction": "/Part2/Introduction.mp4",
  "invalid": "/Part2/Invalid.mp4",
  "invent": "/Part2/invent.mp4",
  "inverse": "/Part2/Inverse.mp4",
  "investment": "/Part2/Investment.mp4",
  "iron": "/Part2/iron-1.mp4",
  "irregular": "/Part2/Irregular.mp4",
  "irreversible": "/Part2/Irreversible.mp4",
  "irrevocable": "/Part2/Irrevocable.mp4",
  "isl intro": "/Part2/ISL Intro.mp4",
  "island": "/Part2/island.mp4",
  "isreal": "/Part2/isreal.mp4",
  "it": "/Part2/it.mp4",
  "item": "/Part2/Item.mp4",
  "its": "/Part2/its.mp4",
  "itself": "/Part2/itself.mp4",
  "jackfruit": "/Part2/jackfruit.mp4",
  "jail": "/Part2/jail.mp4",
  "jailor": "/Part2/jailor.mp4",
  "jain": "/Part2/jain.mp4",
  "jalpur": "/Part2/jalpur.mp4",
  "jam": "/Part2/jam.mp4",
  "jammu kashmir": "/Part2/jammu kashmir.mp4",
  "january": "/Part2/january-1.mp4",
  "jaundice": "/Part2/jaundice.mp4",
  "jealous": "/Part2/jealous.mp4",
  "jeep": "/Part2/jeep.mp4",
  "jesus": "/Part2/jesus.mp4",
  "jew": "/Part2/jew.mp4",
  "job": "/Part2/Job.mp4",
  "join": "/Part2/join.mp4",
  "jouie": "/Part2/Jouie.mp4",
  "joumal": "/Part2/Joumal.mp4",
  "judge": "/Part2/judge-1.mp4",
  "judgement": "/Part2/Judgement.mp4",
  "judicial": "/Part2/Judicial.mp4",
  "juice": "/Part2/juice.mp4",
  "july": "/Part2/july.mp4",
  "jump": "/Part2/jump.mp4",
  "june": "/Part2/june.mp4",
  "junior": "/Part2/Junior.mp4",
  "juplter": "/Part2/Juplter.mp4",
  "justice": "/Part2/justice.mp4",
  "ka ka ka": "/Part2/Ka Ka Ka.mp4",
  "kaieidoscope": "/Part2/Kaieidoscope.mp4",
  "kamataka": "/Part2/kamataka.mp4",
  "kangaroo": "/Part2/kangaroo.mp4",
  "kannada": "/Part2/kannada.mp4",
  "kanpur": "/Part2/kanpur.mp4",
  "karate": "/Part2/karate.mp4",
  "keep": "/Part2/keep.mp4",
  "keeper": "/Part2/Keeper.mp4",
  "keivin": "/Part2/Keivin.mp4",
  "kerala": "/Part2/kerala-1.mp4",
  "key": "/Part2/Key.mp4",
  "kick": "/Part2/kick.mp4",
  "kientical": "/Part2/Kientical.mp4",
  "kill": "/Part2/kill-1.mp4",
  "kilogram": "/Part2/Kilogram.mp4",
  "kilometer": "/Part2/kilometer.mp4",
  "kind": "/Part2/kind.mp4",
  "kinetic energy": "/Part2/Kinetic Energy.mp4",
  "king": "/Part2/king-1.mp4",
  "kiss": "/Part2/kiss.mp4",
  "kitchen": "/Part2/kitchen-1.mp4",
  "kite": "/Part2/kite.mp4",
  "knee": "/Part2/knee.mp4",
  "knife": "/Part2/knife.mp4",
  "knit": "/Part2/knit.mp4",
  "know": "/Part2/know.mp4",
  "knowledge working": "/Part2/Knowledge Working.mp4",
  "knowledge": "/Part2/knowledge.mp4",
  "known loss": "/Part2/Known Loss.mp4",
  "krishna": "/Part2/krishna.mp4",
  "kurta": "/Part2/kurta-1.mp4",
  "l e d": "/Part2/L.E.D.mp4",
  "laboratary": "/Part2/laboratary.mp4",
  "labour": "/Part2/Labour.mp4",
  "labourer": "/Part2/Labourer.mp4",
  "ladder": "/Part2/ladder.mp4",
  "laddu": "/Part2/laddu.mp4",
  "lady is finger": "/Part2/lady is finger.mp4",
  "lake": "/Part2/lake.mp4",
  "lame": "/Part2/lame.mp4",
  "land cess": "/Part2/Land Cess.mp4",
  "land holding": "/Part2/Land Holding.mp4",
  "land revenue": "/Part2/Land Revenue.mp4",
  "land": "/Part2/land.mp4",
  "landlord": "/Part2/Landlord.mp4",
  "lapse": "/Part2/Lapse.mp4",
  "lassi": "/Part2/lassi.mp4",
  "last pay cortificate l p c": "/Part2/Last Pay Cortificate (L.P.C).mp4",
  "late": "/Part2/late-1.mp4",
  "latitude": "/Part2/Latitude.mp4",
  "laugh": "/Part2/laugh.mp4",
  "lawyer": "/Part2/lawyer.mp4",
  "lay off": "/Part2/Lay Off.mp4",
  "lazy": "/Part2/lazy.mp4",
  "ldli": "/Part2/ldli.mp4",
  "lead": "/Part2/lead.mp4",
  "leader": "/Part2/leader.mp4",
  "leaf": "/Part2/leaf.mp4",
  "leafy vegetables": "/Part2/leafy vegetables.mp4",
  "leak": "/Part2/leak.mp4",
  "learn to swim": "/Part2/Learn to swim.mp4",
  "learn": "/Part2/learn-1.mp4",
  "least count": "/Part2/Least Count.mp4",
  "leather": "/Part2/leather.mp4",
  "leave casual lc": "/Part2/Leave Casual (Lc).mp4",
  "leave compensory": "/Part2/Leave Compensory.mp4",
  "leave duty": "/Part2/Leave Duty.mp4",
  "leave extraordinary": "/Part2/Leave Extraordinary.mp4",
  "leave medical": "/Part2/Leave Medical.mp4",
  "leave preparatory to retirement": "/Part2/Leave Preparatory To Retirement.mp4",
  "leave study": "/Part2/Leave Study.mp4",
  "leave": "/Part2/leave.mp4",
  "lecturer": "/Part2/lecturer.mp4",
  "ledger balance": "/Part2/Ledger Balance.mp4",
  "ledger": "/Part2/Ledger.mp4",
  "left": "/Part2/left.mp4",
  "leg": "/Part2/leg.mp4",
  "legal advisor": "/Part2/Legal Advisor.mp4",
  "legal claim": "/Part2/Legal Claim.mp4",
  "legal": "/Part2/Legal.mp4",
  "legally protected": "/Part2/Legally Protected.mp4",
  "lemon": "/Part2/lemon.mp4",
  "lend": "/Part2/lend.mp4",
  "lens": "/Part2/Lens.mp4",
  "leprosy": "/Part2/leprosy.mp4",
  "less": "/Part2/less.mp4",
  "letter of authority": "/Part2/Letter Of Authority.mp4",
  "letter": "/Part2/letter.mp4",
  "level rate": "/Part2/Level Rate.mp4",
  "level": "/Part2/Level.mp4",
  "lew rule": "/Part2/Lew _ Rule.mp4",
  "lgnore": "/Part2/lgnore.mp4",
  "library": "/Part2/library.mp4",
  "licence": "/Part2/Licence.mp4",
  "lick": "/Part2/lick.mp4",
  "lie": "/Part2/lie-1.mp4",
  "life insurance lic": "/Part2/Life Insurance (Lic).mp4",
  "light year": "/Part2/Light Year.mp4",
  "light": "/Part2/Light.mp4",
  "lighthouse": "/Part2/lighthouse.mp4",
  "lightning": "/Part2/lightning.mp4",
  "like": "/Part2/like.mp4",
  "lion": "/Part2/lion.mp4",
  "lips": "/Part2/lips.mp4",
  "lipstick": "/Part2/lipstick.mp4",
  "liquid fueis": "/Part2/Liquid Fueis.mp4",
  "liquid": "/Part2/Liquid.mp4",
  "liquidation": "/Part2/Liquidation.mp4",
  "liquor": "/Part2/liquor.mp4",
  "list": "/Part2/list.mp4",
  "litre": "/Part2/Litre.mp4",
  "little": "/Part2/little.mp4",
  "lizard": "/Part2/lizard.mp4",
  "lnaugurate": "/Part2/lnaugurate.mp4",
  "loan terminable": "/Part2/Loan Terminable.mp4",
  "loan": "/Part2/Loan.mp4",
  "lock": "/Part2/lock.mp4",
  "locker": "/Part2/Locker.mp4",
  "long": "/Part2/long.mp4",
  "longitude": "/Part2/Longitude.mp4",
  "longitudinat wave": "/Part2/Longitudinat Wave.mp4",
  "loose leaf binder": "/Part2/Loose Leaf Binder.mp4",
  "loose": "/Part2/loose.mp4",
  "lorry": "/Part2/lorry-1.mp4",
  "lose": "/Part2/lose.mp4",
  "lotus": "/Part2/lotus.mp4",
  "loud speaker": "/Part2/Loud Speaker.mp4",
  "loud": "/Part2/loud.mp4",
  "love": "/Part2/love.mp4",
  "low": "/Part2/low.mp4",
  "lubrication oil": "/Part2/Lubrication Oil.mp4",
  "lucknow": "/Part2/lucknow.mp4",
  "lucky": "/Part2/lucky.mp4",
  "lumpsum": "/Part2/Lumpsum.mp4",
  "lunancy": "/Part2/Lunancy.mp4",
  "lunar eclipse": "/Part2/Lunar Eclipse.mp4",
  "lunch": "/Part2/lunch.mp4",
  "machine": "/Part2/machine.mp4",
  "machines": "/Part2/Machines.mp4",
  "madhya pradesh": "/Part2/madhya pradesh.mp4",
  "magic": "/Part2/magic-1.mp4",
  "magnet": "/Part2/magnet.mp4",
  "magnetism": "/Part2/Magnetism.mp4",
  "maharastra": "/Part2/maharastra.mp4",
  "mahavir jayanthi": "/Part2/mahavir jayanthi.mp4",
  "mail transfer m t": "/Part2/Mail Transfer (M.T.).mp4",
  "mail": "/Part2/Mail.mp4",
  "main scale": "/Part2/Main Scale.mp4",
  "main": "/Part2/Main.mp4",
  "maintenance allowance": "/Part2/Maintenance Allowance.mp4",
  "major": "/Part2/Major.mp4",
  "majority": "/Part2/Majority.mp4",
  "malyalam": "/Part2/malyalam.mp4",
  "man": "/Part2/man.mp4",
  "management": "/Part2/Management.mp4",
  "mandatory": "/Part2/Mandatory.mp4",
  "mango": "/Part2/mango.mp4",
  "manual of instruction": "/Part2/Manual Of Instruction.mp4",
  "manufacture": "/Part2/Manufacture.mp4",
  "manure": "/Part2/Manure.mp4",
  "many": "/Part2/many.mp4",
  "map": "/Part2/map.mp4",
  "marathi": "/Part2/marathi.mp4",
  "march": "/Part2/march.mp4",
  "margin": "/Part2/Margin.mp4",
  "mark": "/Part2/Mark.mp4",
  "market": "/Part2/market.mp4",
  "mars": "/Part2/Mars.mp4",
  "marth": "/Part2/marth.mp4",
  "mary": "/Part2/mary.mp4",
  "masala": "/Part2/masala.mp4",
  "mason": "/Part2/mason.mp4",
  "masquito": "/Part2/masquito.mp4",
  "mat": "/Part2/mat.mp4",
  "matchbox": "/Part2/matchbox.mp4",
  "material": "/Part2/Material.mp4",
  "mathematical": "/Part2/Mathematical.mp4",
  "mathematics": "/Part2/mathematics.mp4",
  "matural gas": "/Part2/Matural Gas.mp4",
  "maturity": "/Part2/Maturity.mp4",
  "maximum": "/Part2/Maximum.mp4",
  "may": "/Part2/may.mp4",
  "me": "/Part2/me.mp4",
  "measles": "/Part2/measles.mp4",
  "measure": "/Part2/measure-1.mp4",
  "measurement": "/Part2/Measurement.mp4",
  "meat": "/Part2/meat.mp4",
  "mechanic": "/Part2/mechanic.mp4",
  "mechanics": "/Part2/Mechanics.mp4",
  "medicine": "/Part2/medicine.mp4",
  "medium term mtl": "/Part2/Medium Term (Mtl).mp4",
  "meet": "/Part2/meet.mp4",
  "megnet": "/Part2/Megnet.mp4",
  "megnification": "/Part2/Megnification.mp4",
  "melt": "/Part2/melt.mp4",
  "melting point": "/Part2/Melting Point.mp4",
  "memo": "/Part2/Memo.mp4",
  "memorize": "/Part2/memorize.mp4",
  "merchant": "/Part2/Merchant.mp4",
  "mercury": "/Part2/Mercury.mp4",
  "merger": "/Part2/Merger.mp4",
  "merit and demerits": "/Part2/Merit And Demerits.mp4",
  "message": "/Part2/Message.mp4",
  "messenger": "/Part2/Messenger.mp4",
  "meter": "/Part2/meter.mp4",
  "method of accounting": "/Part2/Method Of Accounting.mp4",
  "metre": "/Part2/Metre.mp4",
  "mhale": "/Part2/mhale.mp4",
  "microwave": "/Part2/Microwave.mp4",
  "mile": "/Part2/Mile.mp4",
  "mili litre": "/Part2/mili litre.mp4",
  "milk": "/Part2/milk.mp4",
  "milkman": "/Part2/milkman.mp4",
  "milligram": "/Part2/Milligram.mp4",
  "millilitre": "/Part2/Millilitre.mp4",
  "millimetre": "/Part2/Millimetre.mp4",
  "mime": "/Part2/mime.mp4",
  "minimum": "/Part2/Minimum.mp4",
  "minister": "/Part2/minister.mp4",
  "minor": "/Part2/Minor.mp4",
  "minute": "/Part2/Minute.mp4",
  "minutes": "/Part2/minutes.mp4",
  "mirror": "/Part2/mirror.mp4",
  "misbehaviour": "/Part2/Misbehaviour.mp4",
  "miscellaneous": "/Part2/Miscellaneous.mp4",
  "miss": "/Part2/miss.mp4",
  "missing": "/Part2/Missing.mp4",
  "mistake": "/Part2/Mistake.mp4",
  "mix": "/Part2/mix.mp4",
  "mixer": "/Part2/mixer-1.mp4",
  "mixture": "/Part2/Mixture.mp4",
  "mobilisation deposit": "/Part2/Mobilisation Deposit.mp4",
  "model": "/Part2/model.mp4",
  "modification": "/Part2/Modification.mp4",
  "mogra": "/Part2/mogra.mp4",
  "molecuiar motion": "/Part2/Molecuiar Motion.mp4",
  "molecuie": "/Part2/Molecuie.mp4",
  "monday": "/Part2/monday-1.mp4",
  "monetary": "/Part2/Monetary.mp4",
  "money order": "/Part2/money order.mp4",
  "money": "/Part2/money.mp4",
  "moneylender": "/Part2/Moneylender.mp4",
  "monitoring": "/Part2/Monitoring.mp4",
  "monkey": "/Part2/monkey.mp4",
  "month": "/Part2/month-1.mp4",
  "monthly return": "/Part2/Monthly Return.mp4",
  "monthly statement": "/Part2/Monthly Statement.mp4",
  "moon": "/Part2/moon.mp4",
  "moral": "/Part2/Moral.mp4",
  "more": "/Part2/more.mp4",
  "morning": "/Part2/morning-1.mp4",
  "mortgage": "/Part2/Mortgage.mp4",
  "mosque": "/Part2/mosque.mp4",
  "mosquito": "/Part2/mosquito.mp4",
  "motal": "/Part2/Motal.mp4",
  "mother": "/Part2/mother-1.mp4",
  "mother in law": "/Part2/mother-in-law.mp4",
  "motion": "/Part2/Motion.mp4",
  "motor": "/Part2/motor.mp4",
  "mountain": "/Part2/mountain.mp4",
  "mouth": "/Part2/mouth.mp4",
  "movable property": "/Part2/Movable Property.mp4",
  "move": "/Part2/move.mp4",
  "mud": "/Part2/mud.mp4",
  "mug": "/Part2/mug.mp4",
  "muitimeter": "/Part2/Muitimeter.mp4",
  "multily": "/Part2/multily.mp4",
  "mumbai": "/Part2/mumbai.mp4",
  "mumbs": "/Part2/mumbs.mp4",
  "mumps": "/Part2/mumps.mp4",
  "museum": "/Part2/museum.mp4",
  "music": "/Part2/Music.mp4",
  "muslim": "/Part2/muslim.mp4",
  "mute": "/Part2/mute.mp4",
  "mutual agreement": "/Part2/Mutual Agreement.mp4",
  "my": "/Part2/my.mp4",
  "myself": "/Part2/myself.mp4",
  "mysore": "/Part2/mysore.mp4",
  "nagpur": "/Part2/nagpur.mp4",
  "nail polish": "/Part2/nail polish.mp4",
  "nail": "/Part2/nail.mp4",
  "name": "/Part2/name-1.mp4",
  "narrow": "/Part2/narrow.mp4",
  "national anthem": "/Part2/national anthem.mp4",
  "nationalisation": "/Part2/Nationalisation.mp4",
  "natural gaurdian": "/Part2/Natural Gaurdian.mp4",
  "natural": "/Part2/Natural.mp4",
  "nature is like ferris wheel": "/Part2/Nature is Like Ferris Wheel.mp4",
  "nature of god": "/Part2/Nature of God.mp4",
  "near": "/Part2/near.mp4",
  "necessary": "/Part2/necessary.mp4",
  "neck": "/Part2/neck.mp4",
  "necklace": "/Part2/necklace.mp4",
  "nect tie": "/Part2/nect tie.mp4",
  "need for everthing": "/Part2/Need for everthing_1_BA460E035E03443B894E.mp4",
  "need": "/Part2/need-1.mp4",
  "needle": "/Part2/needle.mp4",
  "negative error": "/Part2/Negative Error.mp4",
  "negative": "/Part2/Negative.mp4",
  "negligence": "/Part2/Negligence.mp4",
  "negligible": "/Part2/Negligible.mp4",
  "negogiable instrumemts": "/Part2/Negogiable Instrumemts.mp4",
  "neighbour": "/Part2/neighbour.mp4",
  "nepal": "/Part2/nepal-1.mp4",
  "neptune": "/Part2/Neptune.mp4",
  "nervous": "/Part2/nervous.mp4",
  "nest": "/Part2/nest.mp4",
  "net profit": "/Part2/Net Profit.mp4",
  "neutral": "/Part2/Neutral.mp4",
  "neutron": "/Part2/Neutron.mp4",
  "never": "/Part2/never.mp4",
  "new moon day": "/Part2/new moon day.mp4",
  "new": "/Part2/new.mp4",
  "newspaper": "/Part2/newspaper.mp4",
  "newton": "/Part2/Newton.mp4",
  "next": "/Part2/next.mp4",
  "night": "/Part2/night-1.mp4",
  "no due certificate": "/Part2/No Due Certificate.mp4",
  "no objection certificate noc": "/Part2/No Objection Certificate (Noc).mp4",
  "noise poiiution": "/Part2/Noise Poiiution.mp4",
  "nominal value": "/Part2/Nominal Value.mp4",
  "nominate": "/Part2/Nominate.mp4",
  "non legal": "/Part2/Non Legal.mp4",
  "non payment": "/Part2/Non Payment.mp4",
  "non resident nri": "/Part2/Non Resident (Nri).mp4",
  "non vegetarian": "/Part2/non vegetarian.mp4",
  "non uniform motion": "/Part2/Non-Uniform Motion-1.mp4",
  "noon": "/Part2/noon.mp4",
  "north america": "/Part2/north america.mp4",
  "north poie": "/Part2/North Poie.mp4",
  "north pole": "/Part2/North Pole.mp4",
  "north": "/Part2/North.mp4",
  "northem hemisphere": "/Part2/Northem Hemisphere.mp4",
  "nose stud": "/Part2/nose stud.mp4",
  "nose": "/Part2/nose.mp4",
  "nosie": "/Part2/Nosie.mp4",
  "not a drop of water": "/Part2/Not a Drop of Water.mp4",
  "not negotiable": "/Part2/Not Negotiable.mp4",
  "notary public": "/Part2/Notary Public.mp4",
  "note book": "/Part2/note book.mp4",
  "note": "/Part2/note.mp4",
  "notice board": "/Part2/Notice Board.mp4",
  "notification": "/Part2/Notification.mp4",
  "november": "/Part2/november.mp4",
  "now": "/Part2/now.mp4",
  "nsck": "/Part2/nsck.mp4",
  "nuclear energy": "/Part2/Nuclear Energy.mp4",
  "nuclear reactor": "/Part2/Nuclear Reactor.mp4",
  "nucleus": "/Part2/Nucleus.mp4",
  "number system": "/Part2/Number System.mp4",
  "numbers": "/Part2/numbers.mp4",
  "nurse": "/Part2/nurse-1.mp4",
  "nut": "/Part2/nut.mp4",
  "oath": "/Part2/oath-1.mp4",
  "obedience": "/Part2/Obedience.mp4",
  "object": "/Part2/Object.mp4",
  "objection": "/Part2/Objection.mp4",
  "observation": "/Part2/Observation.mp4",
  "occupation": "/Part2/Occupation.mp4",
  "octal": "/Part2/Octal.mp4",
  "october": "/Part2/october.mp4",
  "of": "/Part2/of.mp4",
  "off season": "/Part2/Off Season.mp4",
  "off shore banking": "/Part2/Off Shore Banking.mp4",
  "offence": "/Part2/Offence.mp4",
  "office bearer": "/Part2/Office Bearer.mp4",
  "office hours": "/Part2/Office Hours.mp4",
  "office": "/Part2/office.mp4",
  "officer": "/Part2/officer.mp4",
  "official language": "/Part2/Official Language.mp4",
  "official": "/Part2/Official.mp4",
  "officiating": "/Part2/Officiating.mp4",
  "often": "/Part2/often.mp4",
  "ohw": "/Part2/Ohw.mp4",
  "oil": "/Part2/Oil.mp4",
  "old age": "/Part2/old (age).mp4",
  "old time": "/Part2/old (time).mp4",
  "olympics": "/Part2/olympics.mp4",
  "omit": "/Part2/omit.mp4",
  "on demand": "/Part2/On Demand.mp4",
  "on probation": "/Part2/On Probation.mp4",
  "on": "/Part2/on.mp4",
  "onion": "/Part2/onion.mp4",
  "only": "/Part2/only.mp4",
  "ooty": "/Part2/ooty.mp4",
  "opaque": "/Part2/opaque.mp4",
  "open dated": "/Part2/Open Dated.mp4",
  "open": "/Part2/open.mp4",
  "opening balance": "/Part2/Opening Balance.mp4",
  "operate an a c": "/Part2/Operate (An A C).mp4",
  "operation": "/Part2/operation.mp4",
  "opinion": "/Part2/Opinion.mp4",
  "opposite": "/Part2/opposite.mp4",
  "opposition": "/Part2/Opposition.mp4",
  "optical fiber cabte": "/Part2/Optical Fiber Cabte.mp4",
  "orange": "/Part2/Orange.mp4",
  "orbit": "/Part2/Orbit.mp4",
  "order standing": "/Part2/Order Standing.mp4",
  "order": "/Part2/order-1.mp4",
  "original": "/Part2/Original.mp4",
  "oriya": "/Part2/oriya.mp4",
  "ornaments": "/Part2/ornaments.mp4",
  "osciilator": "/Part2/Osciilator.mp4",
  "oscillation": "/Part2/Oscillation.mp4",
  "osclllatory motion": "/Part2/Osclllatory Motion.mp4",
  "osmosis": "/Part2/Osmosis.mp4",
  "our": "/Part2/our.mp4",
  "ourselves": "/Part2/ourselves.mp4",
  "out of date": "/Part2/Out Of Date.mp4",
  "out of print": "/Part2/Out Of Print.mp4",
  "out": "/Part2/out.mp4",
  "output": "/Part2/Output.mp4",
  "outstanding report": "/Part2/Outstanding Report.mp4",
  "outstanding": "/Part2/Outstanding.mp4",
  "over head projector": "/Part2/over head projector.mp4",
  "over writing": "/Part2/Over Writing.mp4",
  "over": "/Part2/over.mp4",
  "overall": "/Part2/Overall.mp4",
  "overdraft od": "/Part2/Overdraft (Od).mp4",
  "overdue": "/Part2/Overdue.mp4",
  "overleaf": "/Part2/Overleaf.mp4",
  "overseas": "/Part2/Overseas.mp4",
  "overtime allowance": "/Part2/Overtime Allowance.mp4",
  "owe": "/Part2/Owe.mp4",
  "owl": "/Part2/owl.mp4",
  "owner cultivated": "/Part2/Owner Cultivated.mp4",
  "packing credit": "/Part2/Packing Credit.mp4",
  "page": "/Part2/page.mp4",
  "paid up capital": "/Part2/Paid Up Capital.mp4",
  "pain": "/Part2/pain.mp4",
  "paint": "/Part2/paint.mp4",
  "paise": "/Part2/paise.mp4",
  "pakistan": "/Part2/pakistan.mp4",
  "pamplet": "/Part2/Pamplet.mp4",
  "pan": "/Part2/pan.mp4",
  "pant": "/Part2/pant.mp4",
  "papaya": "/Part2/papaya.mp4",
  "paper": "/Part2/paper.mp4",
  "pappad": "/Part2/pappad.mp4",
  "par above": "/Part2/Par - Above.mp4",
  "par at": "/Part2/Par - At.mp4",
  "par below": "/Part2/Par - Below.mp4",
  "paraboia": "/Part2/Paraboia.mp4",
  "parachute": "/Part2/Parachute.mp4",
  "paraitel circuit": "/Part2/Paraitel Circuit.mp4",
  "parallel": "/Part2/Parallel.mp4",
  "parent branch": "/Part2/Parent Branch.mp4",
  "parent": "/Part2/parent.mp4",
  "parental": "/Part2/Parental.mp4",
  "parents": "/Part2/parents.mp4",
  "parliament": "/Part2/parliament.mp4",
  "parrot": "/Part2/parrot.mp4",
  "parsi": "/Part2/parsi.mp4",
  "part 2": "/Part2/PART 2.mp4",
  "part time": "/Part2/Part Time.mp4",
  "participation": "/Part2/Participation.mp4",
  "particular": "/Part2/Particular.mp4",
  "particulars": "/Part2/Particulars.mp4",
  "partly paid": "/Part2/Partly Paid.mp4",
  "partner": "/Part2/Partner.mp4",
  "partnership deed": "/Part2/Partnership Deed.mp4",
  "partnership": "/Part2/Partnership.mp4",
  "pass book": "/Part2/Pass Book.mp4",
  "pass to": "/Part2/Pass To.mp4",
  "pass": "/Part2/Pass.mp4",
  "passing official": "/Part2/Passing Official.mp4",
  "passive debt": "/Part2/Passive Debt.mp4",
  "password": "/Part2/Password.mp4",
  "patience": "/Part2/patience.mp4",
  "patna": "/Part2/patna.mp4",
  "paw": "/Part2/paw.mp4",
  "paws": "/Part2/paws.mp4",
  "pay": "/Part2/pay.mp4",
  "payee": "/Part2/Payee.mp4",
  "paying slip": "/Part2/Paying Slip.mp4",
  "peacock": "/Part2/peacock.mp4",
  "peak": "/Part2/peak.mp4",
  "peas": "/Part2/peas.mp4",
  "peep": "/Part2/peep.mp4",
  "pen": "/Part2/pen-1.mp4",
  "penal interest": "/Part2/Penal Interest.mp4",
  "pencil": "/Part2/pencil-1.mp4",
  "penduium": "/Part2/Penduium.mp4",
  "pentode": "/Part2/Pentode.mp4",
  "peon": "/Part2/peon.mp4",
  "pepper": "/Part2/pepper.mp4",
  "per pro": "/Part2/Per Pro.mp4",
  "percentage": "/Part2/percentage.mp4",
  "perfect": "/Part2/Perfect-1.mp4",
  "period": "/Part2/Period.mp4",
  "periscope": "/Part2/Periscope.mp4",
  "permanent": "/Part2/Permanent.mp4",
  "perpendicular": "/Part2/Perpendicular.mp4",
  "person": "/Part2/person.mp4",
  "peteti": "/Part2/peteti.mp4",
  "petrol": "/Part2/Petrol.mp4",
  "photograph": "/Part2/photograph.mp4",
  "photographic camera": "/Part2/Photographic Camera.mp4",
  "photographic plate": "/Part2/Photographic Plate.mp4",
  "phyaical balance": "/Part2/Phyaical Balance.mp4",
  "physical training": "/Part2/physical training.mp4",
  "physics": "/Part2/Physics-1.mp4",
  "pick": "/Part2/pick.mp4",
  "pickle": "/Part2/pickle.mp4",
  "picture": "/Part2/picture.mp4",
  "pig": "/Part2/pig-1.mp4",
  "pillow": "/Part2/pillow-1.mp4",
  "pilot": "/Part2/pilot.mp4",
  "pink": "/Part2/Pink.mp4",
  "pipe": "/Part2/pipe.mp4",
  "piston": "/Part2/Piston.mp4",
  "plan": "/Part2/plan.mp4",
  "plane concave lens": "/Part2/Plane Concave Lens.mp4",
  "plane convex lens": "/Part2/Plane Convex Lens.mp4",
  "plane mirror": "/Part2/Plane Mirror.mp4",
  "plane": "/Part2/Plane.mp4",
  "planet": "/Part2/Planet.mp4",
  "plant": "/Part2/plant.mp4",
  "plasma": "/Part2/Plasma.mp4",
  "plastic": "/Part2/plastic.mp4",
  "plate": "/Part2/plate.mp4",
  "play": "/Part2/play-1.mp4",
  "plgments": "/Part2/Plgments.mp4",
  "plough": "/Part2/plough.mp4",
  "plug": "/Part2/plug.mp4",
  "plumber": "/Part2/plumber.mp4",
  "pluto": "/Part2/Pluto.mp4",
  "poie": "/Part2/Poie.mp4",
  "point": "/Part2/point.mp4",
  "poision": "/Part2/poision-1.mp4",
  "poiygon": "/Part2/Poiygon.mp4",
  "pole": "/Part2/Pole.mp4",
  "police station": "/Part2/police station.mp4",
  "police": "/Part2/police-1.mp4",
  "polish": "/Part2/polish.mp4",
  "poltution": "/Part2/Poltution.mp4",
  "pomogranate": "/Part2/pomogranate.mp4",
  "pond": "/Part2/pond.mp4",
  "pongal": "/Part2/pongal.mp4",
  "poor": "/Part2/poor-1.mp4",
  "positive error": "/Part2/Positive Error.mp4",
  "posltive": "/Part2/Posltive.mp4",
  "possible": "/Part2/possible.mp4",
  "post card": "/Part2/post card.mp4",
  "post dated": "/Part2/Post Dated.mp4",
  "post office": "/Part2/post office.mp4",
  "poster": "/Part2/poster.mp4",
  "posting": "/Part2/Posting.mp4",
  "postman": "/Part2/postman.mp4",
  "postpone": "/Part2/postpone.mp4",
  "potato": "/Part2/potato.mp4",
  "potential energy": "/Part2/Potential Energy.mp4",
  "potentiality": "/Part2/Potentiality.mp4",
  "potentiometer": "/Part2/Potentiometer.mp4",
  "pour": "/Part2/pour.mp4",
  "powder": "/Part2/powder.mp4",
  "power": "/Part2/Power.mp4",
  "practical": "/Part2/Practical.mp4",
  "practise": "/Part2/practise-1.mp4",
  "praise": "/Part2/praise-1.mp4",
  "pray": "/Part2/pray.mp4",
  "pre paid": "/Part2/Pre Paid.mp4",
  "precaution": "/Part2/Precaution.mp4",
  "predecessor": "/Part2/Predecessor.mp4",
  "preliminary": "/Part2/Preliminary.mp4",
  "premature": "/Part2/Premature.mp4",
  "premises": "/Part2/Premises.mp4",
  "premium": "/Part2/Premium.mp4",
  "prescribe sign 2": "/Part2/Prescribe(Sign-2).mp4",
  "prescription": "/Part2/prescription.mp4",
  "present": "/Part2/present.mp4",
  "president": "/Part2/president.mp4",
  "press": "/Part2/press.mp4",
  "pressure": "/Part2/Pressure.mp4",
  "pretend": "/Part2/pretend-1.mp4",
  "previous": "/Part2/Previous.mp4",
  "price": "/Part2/Price.mp4",
  "priest": "/Part2/priest-1.mp4",
  "primary": "/Part2/Primary.mp4",
  "prime minister": "/Part2/prime minister.mp4",
  "principal": "/Part2/principal.mp4",
  "printod circuit board": "/Part2/Printod Circuit Board.mp4",
  "priority": "/Part2/Priority.mp4",
  "prism": "/Part2/Prism.mp4",
  "probing": "/Part2/Probing.mp4",
  "procedure": "/Part2/Procedure.mp4",
  "proceeding": "/Part2/Proceeding.mp4",
  "process": "/Part2/Process.mp4",
  "produce": "/Part2/Produce.mp4",
  "product": "/Part2/Product.mp4",
  "profession": "/Part2/profession.mp4",
  "professional": "/Part2/Professional.mp4",
  "profit": "/Part2/profit-1.mp4",
  "proforma": "/Part2/Proforma.mp4",
  "programme": "/Part2/Programme.mp4",
  "progress": "/Part2/Progress.mp4",
  "project": "/Part2/Project.mp4",
  "projectile motion": "/Part2/Projectile Motion.mp4",
  "projector": "/Part2/Projector.mp4",
  "promise": "/Part2/promise-1.mp4",
  "promisory note": "/Part2/Promisory Note.mp4",
  "promotion": "/Part2/Promotion.mp4",
  "prompt action": "/Part2/Prompt Action.mp4",
  "property landed": "/Part2/Property Landed.mp4",
  "property public": "/Part2/Property Public.mp4",
  "property tax": "/Part2/Property Tax.mp4",
  "property": "/Part2/Property.mp4",
  "proprietory": "/Part2/Proprietory.mp4",
  "propsgation": "/Part2/Propsgation.mp4",
  "prosecution": "/Part2/Prosecution.mp4",
  "prospectus": "/Part2/Prospectus.mp4",
  "protest": "/Part2/Protest.mp4",
  "proton": "/Part2/Proton.mp4",
  "proud": "/Part2/proud.mp4",
  "prove": "/Part2/prove.mp4",
  "provident fund pf": "/Part2/Provident Fund (Pf).mp4",
  "provision": "/Part2/Provision.mp4",
  "public": "/Part2/Public.mp4",
  "publication": "/Part2/Publication.mp4",
  "publish": "/Part2/publish.mp4",
  "puja": "/Part2/puja.mp4",
  "pull": "/Part2/pull.mp4",
  "pump": "/Part2/Pump.mp4",
  "punctual": "/Part2/punctual.mp4",
  "pune": "/Part2/pune.mp4",
  "punishment": "/Part2/punishment.mp4",
  "punjab": "/Part2/punjab.mp4",
  "punpkin": "/Part2/punpkin.mp4",
  "puppet show": "/Part2/puppet show.mp4",
  "purchase hire": "/Part2/Purchase - Hire.mp4",
  "purchase retum": "/Part2/Purchase Retum.mp4",
  "purchase": "/Part2/Purchase.mp4",
  "pure": "/Part2/pure.mp4",
  "puri": "/Part2/puri.mp4",
  "purpose": "/Part2/Purpose.mp4",
  "push": "/Part2/push.mp4",
  "put up": "/Part2/Put Up.mp4",
  "put": "/Part2/put.mp4",
  "pyjama": "/Part2/pyjama.mp4",
  "pyramid": "/Part2/Pyramid.mp4",
  "quadraplicate": "/Part2/Quadraplicate.mp4",
  "qualification essential": "/Part2/Qualification Essential.mp4",
  "qualification": "/Part2/Qualification.mp4",
  "qualified": "/Part2/Qualified.mp4",
  "quality control": "/Part2/Quality Control.mp4",
  "quality": "/Part2/Quality.mp4",
  "quantity": "/Part2/Quantity.mp4",
  "quarter ended": "/Part2/Quarter Ended.mp4",
  "queen": "/Part2/queen-1.mp4",
  "query": "/Part2/Query.mp4",
  "questionable": "/Part2/Questionable.mp4",
  "questionnaire": "/Part2/Questionnaire.mp4",
  "questions": "/Part2/questions.mp4",
  "quick": "/Part2/quick.mp4",
  "quit": "/Part2/Quit.mp4",
  "quota": "/Part2/Quota.mp4",
  "quotation": "/Part2/Quotation.mp4",
  "quote": "/Part2/quote.mp4",
  "quran": "/Part2/quran.mp4",
  "rabbit": "/Part2/rabbit.mp4",
  "race": "/Part2/race.mp4",
  "raddish": "/Part2/raddish.mp4",
  "radio wave": "/Part2/Radio Wave.mp4",
  "radio": "/Part2/Radio.mp4",
  "raid": "/Part2/Raid.mp4",
  "railway station": "/Part2/railway station.mp4"
};
